apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  type: LoadBalancer
  ports:
  - port: 5672
  - port: 15672
    targetPort: http 
  selector:
    app: taskQueue
    component: rabbitmq
